#!/bin/sh
f=`cat /tmp/sjfx-dataloader_flush.out | wc -l`
t=`tail -3 /tmp/sjfx-dataloader_flush.out`


if [ $f == 0 ]
then
   echo "check_sjfx_dataloader_flush   is OK !!! "
   exit 0
else
   echo "$t!!!"
   exit 2
fi